version: "3.8"
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file: ./.env
    ports:
      - "8000:8000"

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    env_file: ./.env
    container_name: frontend
    ports:
      - "3000:5173"
    depends_on:
      - server
